### ISSUE TITLE
ERROR with algo2

### ISSUE THREAD

**Issue by RusseII** [pillargg/pillar_algos#12]
Error with algo2: 

I sent a dataset that is failing via slack. 981828174

[ERROR] IndexError: single positional indexer is out-of-boundsTraceback (most recent call last):  File "/var/task/handler.py", line 34, in handler    algo2_result = algo2.run(all_messages)  File "/var/task/pillaralgos/algo2.py", line 118, in run    results, first_stamp = thalamus(big_df, min_)  File "/var/task/pillaralgos/algo2.py", line 40, in thalamus    hour = chunk.iloc[-1,11] # col 11 is hour.  File "/var/task/pandas/core/indexing.py", line 889, in __getitem__    return self._getitem_tuple(key)  File "/var/task/pandas/core/indexing.py", line 1450, in _getitem_tuple    self._has_valid_tuple(tup)  File "/var/task/pandas/core/indexing.py", line 723, in _has_valid_tuple    self._validate_key(k, i)  File "/var/task/pandas/core/indexing.py", line 1358, in _validate_key    self._validate_integer(key, axis)  File "/var/task/pandas/core/indexing.py", line 1444, in _validate_integer    raise IndexError("single positional indexer is out-of-bounds")

**Comment by pomkos** [comment]
Looks like there was a chunk with just one timestamp in it? I'll check it out

**Comment by pomkos** [comment]
From Russ: 160/200 datasets had this issue.

**Comment by pomkos** [comment]
@RusseII it would be helpful if I can automate grabbing 5 random transcripts from aws to test algos on. Also posted in slack #all-hands channel

**Comment by pomkos** [comment]
https://github.com/pillargg/twitch_chat_analysis/blob/46c0415a6646a7f346db9054a85f0e02f8af8891/pypi/pillaralgos/algo2.py#L40

**Comment by RusseII** [comment]
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-example-download-file.html
Use API to list buckets, then api to download everything from the buckets


I sent you the API keys you'll need on PM https://boto3.amazonaws.com/v1/documentation/api/latest/guide/quickstart.html#configuration

**Comment by pomkos** [comment]
Made line relative, no more referencing index position of columns. Pushing pypi.
