### ISSUE TITLE
Algorithm 2 is often buggy

### ISSUE THREAD

**Issue by RusseII** [pillargg/pillar_algos#21]
![image](https://user-images.githubusercontent.com/15036618/114547227-c8b49b80-9c23-11eb-995c-5cd4f20ffb2e.png) (makes 5 clips with only one minute of chat data)

![image](https://user-images.githubusercontent.com/15036618/114547377-fef21b00-9c23-11eb-91d4-1b9a9b22d530.png)( only 5 seconds long) https://dev.pillar.gg/videos/981521027

**Comment by pomkos** [comment]
Weird. I'll take a look today.

**Comment by pomkos** [comment]
![image](https://user-images.githubusercontent.com/8731022/114557868-1d621180-9c38-11eb-979a-6e7f5ee1a510.png)

Weird af

**Comment by pomkos** [comment]
Ya turns out I forgot to take the means of each chunk. So the results actually represent "what time did this unique person start and stop chatting" lmao.

Sidenote: this is why I BEGGED for an algo review with some people

Edit: Im gonna make a mini unit test for each algo

**Comment by pomkos** [comment]
Closing and pushing.
