### ISSUE TITLE
Combine multiple algorithms? 

### ISSUE THREAD

**Issue by RusseII** [pillargg/pillar_algos#23]
When viewing the clips I noticed that the best clips were often picked up by several of the algorithms. Would it make sense to look across all the algorithms and see which clips were identified by multiple of the algorithms and assume those clips are better? Or does that not make sense?

**Comment by pomkos** [comment]
Yes, please see the readme for more details.

**Comment by pomkos** [comment]
Oh you mean look at timestamps. Sure, should be easy enough to implement.

**Comment by pomkos** [comment]
Done, with unit test yay. Script [here](https://github.com/pillargg/twitch_chat_analysis/blob/thalamus/prod/pillaralgos/brain.py). 

`pip install pillaralgos==1.0.11`

```
from pillaralgos import brain
json = brain.run(data, x=1, limit=None)
```

**Comment by pomkos** [comment]
Let me know how it works

**Comment by chand1012** [comment]
Has this been completed? Seems like #30 would close this.

**Comment by pomkos** [comment]
I'm gonna close it. @RusseII reopen if you find issues.
