### ISSUE TITLE
Setting _min parameter causes bugs

### ISSUE THREAD

**Issue by RusseII** [pillargg/pillar_algos#31]
https://dev.pillar.gg/videos/987762179

version 1.0.10 pillaralgo

![image](https://user-images.githubusercontent.com/15036618/115015026-b2534d80-9e78-11eb-8549-5dbba765f660.png)

1st algo seems to work fine. 
2nd has 0s timestamps
3 and 4 still have 2 min long timestamps

**Comment by pomkos** [comment]
This was fixed in 1.0.11

**Comment by pomkos** [comment]
Wait where did you set them? Is this a new bug? @RusseII

**Comment by RusseII** [comment]
#22

**Comment by RusseII** [comment]
> Wait where did you set them? Is this a new bug? @RusseII

https://github.com/pillargg/timestamps/blob/51f6eb1dcff20f7367f0d0349dab3b662b7372ae/lambdas/clipfinder/handler.py#L34

**Comment by pomkos** [comment]
Oh ok. This was fixed in 1.0.11.

**Comment by RusseII** [comment]
> 3 and 4 still have 2 min long timestamps

That was fixed as well?

**Comment by pomkos** [comment]
yes

**Comment by pomkos** [comment]
Double checked. I guess I never committed, cuz 3/3.5 are still 2 min on 0.11. Sorry for me.
