### ISSUE TITLE
LIMIT parameter does not work as intended.

### ISSUE THREAD

**Issue by RusseII** [pillargg/pillar_algos#36]
![image](https://user-images.githubusercontent.com/15036618/115114474-3f6bd480-9f55-11eb-85d7-ff3b411d62c1.png)

When setting the limit parameter on algo1 (and probably the others) it does not get the X best clips. It gets the X first clips.

For example, when I set limit to 5, it only gets clips from the first couple minutes of the stream. It should return the 5 BEST clips from the entire stream

**Comment by pomkos** [comment]
Fixed. `pip install pillaralgos==1.0.12`
