### ISSUE TITLE
Brain v1.0.12 does not work

### ISSUE THREAD

**Issue by RusseII** [pillargg/pillar_algos#37]
`brain_results = brain.run(all_messages, clip_length=.75, limit=10)`
 
 {"errorMessage": "'chats_per_0.5min'", "errorType": "KeyError", "stackTrace": ["  File \"/var/task/handler.py\", line 33, in handler\n    algo2_result = algo2.run(all_messages, min_=.5,  limit=10)\n", "  File \"/var/task/pillaralgos/algo2.py\", line 144, in run\n    json_results = d.results_jsonified(results, first_stamp, f\"chats_per_{min_}min\")\n", "  File \"/var/task/pillaralgos/helpers/data_handler.py\", line 304, in results_jsonified\n    results = results.sort_values(\n", "  File \"/var/task/pandas/core/frame.py\", line 5455, in sort_values\n    k = self._get_label_or_level_values(by, axis=axis)\n", "  File \"/var/task/pandas/core/generic.py\", line 1684, in _get_label_or_level_values\n    raise KeyError(key)\n"]}%          

Input data - https://slstack-messagestore60e7afc8-fcvaaengplyv.s3.amazonaws.com/963184458

**Comment by pomkos** [comment]
Its going to take me a while to resolve issues at this time, if someone else could take this one I'd appreciate it.

**Comment by pomkos** [comment]
I could not replicate the bug using 1.0.12 from pypi. 

`pip install pillaralgos==1.0.12`

<img width="459" alt="image" src="https://user-images.githubusercontent.com/8731022/116795309-a3d07d00-aa99-11eb-8cc6-1f0a69032078.png">

**Comment by pomkos** [comment]
Confirmed works for `clip_length = 0.75` as well. @RusseII 

<img width="481" alt="image" src="https://user-images.githubusercontent.com/8731022/116837496-5125bc80-ab90-11eb-8b1a-e834ab90be40.png">

**Comment by RusseII** [comment]
> Confirmed works for `clip_length = 0.75` as well. @RusseII
> 
> <img alt="image" width="481" src="https://user-images.githubusercontent.com/8731022/116837496-5125bc80-ab90-11eb-8b1a-e834ab90be40.png">

Why are all of these clip times 110+ seconds? They should be .75 * 60 = 45 seconds. 

example from first clip in your image: 12926 - 12849 = 77 seconds
example from 2nd clip: 3285 - 3405 = 120

**Comment by pomkos** [comment]
weird

**Comment by pomkos** [comment]
`pip install pillaralgos==1.0.13`

Let me know if it worked.

**Comment by pomkos** [comment]
Also updated `test_brain.py` to test for both answer and the answer length.
