### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by chand1012** [pillargg/pillar_algos#6]
CI and CD from [this](https://github.com/pillargg/pillar-queue-wrapper/tree/master/.github/workflows) repo should be replicated here. This includes automatic release publishing and PR linting, possibly documentation generation as well.

**Comment by chand1012** [comment]
#17 and #18 are closely related to this, and I think I will wait until #17 is done before I add CI/CD.

**Comment by chand1012** [comment]
I added unit testing CI in #30 but I am going to wait to add publishing & linting until the PR is merged. CI for documentation generation will be added in #18 .

**Comment by pomkos** [comment]
Does unit testing on github update whenever my new unit test edits/creations get merged to main?

**Comment by chand1012** [comment]
When you add a new unit test it will automatically be added by Pytest.
